spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_platform?useSSL=false&serverTimezone=UTC&allowPu
    username: root
    password: 31052001
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

management:
  server:
    port: 9081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.mihaela.orderplatform: DEBUG

